services:
  dlfile_cp:
    build: .
    volumes:
      - ${CONFIG_PATH:-./configs}:/work/configs
      - ${TARGET_DIRECTORY:-./download}:/work/data
      - ./scripts:/work/scripts
      - ${SSH_AUTH_SOCK}:/tmp/ssh-agent.sock
        # user: "${UID}:${GID}"
    environment:
      DATE_NUM: ${DATE_NUM}
      SSH_AUTH_SOCK: /tmp/ssh-agent.sock
      REMOTE_HOST: ${REMOTE_HOST}
      REMOTE_USER: ${REMOTE_USER}

