services:
  dlfile_cp:
    build: .
    volumes:
      - ${CONFIG_PATH:-./configs}:/work/configs
      - ${TARGET_DIRECTORY:-./download}:/work/data
      - ./scripts:/work/scripts

      # 開発用
      - ./testdata:/work/testdata
      - ${SSH_AUTH_SOCK}:/tmp/ssh-agent.sock
    user: "{UID}:{GID}"
    environment:
      DATE_NUM: "2026-03-05"
      SSH_AUTH_SOCK: /tmp/ssh-agent.sock
      REMOTE_HOST: ${REMOTE_HOST}
      REMOTE_USER: ${REMOTE_USER}

      # - ../source_data:/work/source_data
